#!/bin/bash
# Generate database schema from pattern type
# Usage: ./generate-schema.sh <pattern-type> <output-file>

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$(dirname "$SCRIPT_DIR")/templates"

PATTERN_TYPE="${1}"
OUTPUT_FILE="${2}"

if [ -z "$PATTERN_TYPE" ] || [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: $0 <pattern-type> <output-file>"
    echo ""
    echo "Pattern types:"
    echo "  chat              - Chat/conversation system"
    echo "  rag               - RAG document storage with pgvector"
    echo "  multi-tenant      - Organization-based multi-tenancy"
    echo "  user-management   - Extended user profiles"
    echo "  ai-usage          - Token tracking and usage analytics"
    echo "  complete          - All patterns combined"
    exit 1
fi

# Validate pattern type
case "$PATTERN_TYPE" in
    chat|rag|multi-tenant|user-management|ai-usage|complete)
        ;;
    *)
        echo "Error: Invalid pattern type '$PATTERN_TYPE'"
        echo "Valid types: chat, rag, multi-tenant, user-management, ai-usage, complete"
        exit 1
        ;;
esac

# Create output file with header
cat > "$OUTPUT_FILE" << 'EOF'
-- Generated Schema Migration
-- Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
-- Pattern type: ${PATTERN_TYPE}
--
-- This migration was generated by supabase/skills/schema-patterns
-- Review carefully before applying to production

-- Enable required extensions
create extension if not exists "uuid-ossp";

EOF

# Add pgvector extension for RAG or complete patterns
if [ "$PATTERN_TYPE" = "rag" ] || [ "$PATTERN_TYPE" = "complete" ]; then
    echo "create extension if not exists vector;" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
fi

# Generate schema based on pattern type
case "$PATTERN_TYPE" in
    chat)
        cat "$TEMPLATES_DIR/chat-schema.sql" >> "$OUTPUT_FILE"
        ;;
    rag)
        cat "$TEMPLATES_DIR/rag-schema.sql" >> "$OUTPUT_FILE"
        ;;
    multi-tenant)
        cat "$TEMPLATES_DIR/multi-tenant-schema.sql" >> "$OUTPUT_FILE"
        ;;
    user-management)
        cat "$TEMPLATES_DIR/user-management-schema.sql" >> "$OUTPUT_FILE"
        ;;
    ai-usage)
        cat "$TEMPLATES_DIR/ai-usage-tracking-schema.sql" >> "$OUTPUT_FILE"
        ;;
    complete)
        # Combine all schemas in dependency order
        echo "-- User Management Schema" >> "$OUTPUT_FILE"
        cat "$TEMPLATES_DIR/user-management-schema.sql" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        echo "-- Multi-Tenant Schema" >> "$OUTPUT_FILE"
        cat "$TEMPLATES_DIR/multi-tenant-schema.sql" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        echo "-- Chat Schema" >> "$OUTPUT_FILE"
        cat "$TEMPLATES_DIR/chat-schema.sql" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        echo "-- RAG Schema" >> "$OUTPUT_FILE"
        cat "$TEMPLATES_DIR/rag-schema.sql" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        echo "-- AI Usage Tracking Schema" >> "$OUTPUT_FILE"
        cat "$TEMPLATES_DIR/ai-usage-tracking-schema.sql" >> "$OUTPUT_FILE"
        ;;
esac

# Substitute variables
sed -i "s|\$(date -u +\"%Y-%m-%d %H:%M:%S UTC\")|$(date -u +"%Y-%m-%d %H:%M:%S UTC")|g" "$OUTPUT_FILE"
sed -i "s|\${PATTERN_TYPE}|${PATTERN_TYPE}|g" "$OUTPUT_FILE"

echo "✓ Generated $PATTERN_TYPE schema → $OUTPUT_FILE"
echo ""
echo "Next steps:"
echo "  1. Review: cat $OUTPUT_FILE"
echo "  2. Validate: ./scripts/validate-schema.sh $OUTPUT_FILE"
echo "  3. Apply: ./scripts/apply-migration.sh $OUTPUT_FILE <migration-name>"
