#!/bin/bash

# setup-jwt.sh
# Clerk JWT template configuration and validation

set -e

TEMPLATE_NAME="${1:-default}"

echo "=== Clerk JWT Template Setup ==="
echo "Template: $TEMPLATE_NAME"
echo ""

# Template definitions
declare -A TEMPLATES

# Default template
TEMPLATES[default]=$(cat <<'EOF'
{
  "aud": "authenticated",
  "exp": "{{session.expire_at}}",
  "iat": "{{session.created_at}}",
  "iss": "{{instance.id}}",
  "nbf": "{{session.created_at}}",
  "sid": "{{session.id}}",
  "sub": "{{user.id}}",
  "email": "{{user.primary_email_address}}",
  "email_verified": "{{user.primary_email_address_verified}}",
  "name": "{{user.full_name}}",
  "metadata": "{{user.public_metadata}}"
}
EOF
)

# Hasura template
TEMPLATES[hasura]=$(cat <<'EOF'
{
  "https://hasura.io/jwt/claims": {
    "x-hasura-default-role": "{{user.public_metadata.hasura_role}}",
    "x-hasura-allowed-roles": "{{user.public_metadata.hasura_roles}}",
    "x-hasura-user-id": "{{user.id}}",
    "x-hasura-org-id": "{{org.id}}"
  },
  "sub": "{{user.id}}",
  "email": "{{user.primary_email_address}}"
}
EOF
)

# Supabase template
TEMPLATES[supabase]=$(cat <<'EOF'
{
  "aud": "authenticated",
  "exp": "{{session.expire_at}}",
  "sub": "{{user.id}}",
  "email": "{{user.primary_email_address}}",
  "phone": "{{user.primary_phone_number}}",
  "app_metadata": {
    "provider": "clerk",
    "providers": ["clerk"]
  },
  "user_metadata": "{{user.public_metadata}}",
  "role": "authenticated"
}
EOF
)

# Custom business logic template
TEMPLATES[custom]=$(cat <<'EOF'
{
  "sub": "{{user.id}}",
  "email": "{{user.primary_email_address}}",
  "name": "{{user.full_name}}",
  "role": "{{user.public_metadata.role}}",
  "org_id": "{{org.id}}",
  "org_role": "{{org_membership.role}}",
  "org_slug": "{{org.slug}}",
  "permissions": "{{org_membership.permissions}}",
  "plan": "{{user.public_metadata.subscription_plan}}",
  "metadata": "{{user.public_metadata}}",
  "created_at": "{{user.created_at}}"
}
EOF
)

# Check if template exists
if [ -z "${TEMPLATES[$TEMPLATE_NAME]}" ]; then
    echo "Error: Unknown template '$TEMPLATE_NAME'"
    echo ""
    echo "Available templates:"
    echo "  default  - Standard user claims"
    echo "  hasura   - Hasura GraphQL integration"
    echo "  supabase - Supabase integration"
    echo "  custom   - Custom business logic claims"
    echo ""
    echo "Usage: $0 <template-name>"
    exit 1
fi

# Create JWT templates directory
mkdir -p .clerk/jwt-templates

# Write template to file
TEMPLATE_FILE=".clerk/jwt-templates/$TEMPLATE_NAME.json"
echo "${TEMPLATES[$TEMPLATE_NAME]}" > "$TEMPLATE_FILE"
echo "✓ Created JWT template: $TEMPLATE_FILE"
echo ""

# Display template
echo "Template Contents:"
echo "---"
cat "$TEMPLATE_FILE"
echo "---"
echo ""

# Generate TypeScript types for custom claims
TYPES_FILE=".clerk/jwt-templates/$TEMPLATE_NAME.types.ts"
cat > "$TYPES_FILE" <<EOF
// TypeScript types for JWT template: $TEMPLATE_NAME
// Auto-generated by setup-jwt.sh

export interface ClerkJWTClaims {
  // Standard JWT claims
  iss: string;  // Issuer (Clerk instance ID)
  sub: string;  // Subject (user ID)
  aud: string;  // Audience
  exp: number;  // Expiration timestamp
  iat: number;  // Issued at timestamp
  nbf: number;  // Not before timestamp
  sid: string;  // Session ID

  // User claims
  email?: string;
  email_verified?: boolean;
  name?: string;
  phone?: string;

EOF

# Add template-specific types
case $TEMPLATE_NAME in
    hasura)
        cat >> "$TYPES_FILE" <<EOF
  // Hasura-specific claims
  'https://hasura.io/jwt/claims': {
    'x-hasura-default-role': string;
    'x-hasura-allowed-roles': string[];
    'x-hasura-user-id': string;
    'x-hasura-org-id'?: string;
  };
EOF
        ;;
    supabase)
        cat >> "$TYPES_FILE" <<EOF
  // Supabase-specific claims
  role: 'authenticated' | 'anon';
  app_metadata: {
    provider: string;
    providers: string[];
  };
  user_metadata?: Record<string, unknown>;
EOF
        ;;
    custom)
        cat >> "$TYPES_FILE" <<EOF
  // Custom business logic claims
  role?: string;
  org_id?: string;
  org_role?: string;
  org_slug?: string;
  permissions?: string[];
  plan?: string;
  metadata?: Record<string, unknown>;
  created_at?: number;
EOF
        ;;
    *)
        cat >> "$TYPES_FILE" <<EOF
  // Custom metadata
  metadata?: Record<string, unknown>;
EOF
        ;;
esac

cat >> "$TYPES_FILE" <<EOF
}

// Helper to safely access custom claims
export function getCustomClaims(sessionClaims: unknown): ClerkJWTClaims {
  return sessionClaims as ClerkJWTClaims;
}
EOF

echo "✓ Created TypeScript types: $TYPES_FILE"
echo ""

# Create setup instructions
INSTRUCTIONS_FILE=".clerk/jwt-templates/$TEMPLATE_NAME-setup.md"
cat > "$INSTRUCTIONS_FILE" <<EOF
# JWT Template Setup: $TEMPLATE_NAME

Generated: $(date)

## Dashboard Configuration

1. Go to Clerk Dashboard → JWT Templates
2. Click "New Template" or edit existing template
3. Copy the JSON from \`$TEMPLATE_FILE\`
4. Set as default template for your application
5. Save changes

## Template JSON

\`\`\`json
$(cat "$TEMPLATE_FILE")
\`\`\`

## TypeScript Integration

Import the types in your code:

\`\`\`typescript
import { auth } from '@clerk/nextjs/server';
import { ClerkJWTClaims, getCustomClaims } from './.clerk/jwt-templates/$TEMPLATE_NAME.types';

export async function GET() {
  const { sessionClaims } = await auth();
  const claims = getCustomClaims(sessionClaims);

  // Type-safe access to custom claims
  const userId = claims.sub;
  const email = claims.email;
EOF

# Add template-specific usage examples
case $TEMPLATE_NAME in
    hasura)
        cat >> "$INSTRUCTIONS_FILE" <<EOF
  const hasuraClaims = claims['https://hasura.io/jwt/claims'];
  const role = hasuraClaims['x-hasura-default-role'];
  const orgId = hasuraClaims['x-hasura-org-id'];
EOF
        ;;
    supabase)
        cat >> "$INSTRUCTIONS_FILE" <<EOF
  const role = claims.role; // 'authenticated'
  const metadata = claims.user_metadata;
EOF
        ;;
    custom)
        cat >> "$INSTRUCTIONS_FILE" <<EOF
  const userRole = claims.role;
  const orgId = claims.org_id;
  const permissions = claims.permissions || [];
  const plan = claims.plan;
EOF
        ;;
esac

cat >> "$INSTRUCTIONS_FILE" <<EOF

  return Response.json({ userId, email });
}
\`\`\`

## Required Metadata Setup

EOF

# Add metadata setup instructions
case $TEMPLATE_NAME in
    hasura)
        cat >> "$INSTRUCTIONS_FILE" <<EOF
For Hasura integration, set user metadata:

\`\`\`typescript
await clerkClient.users.updateUser(userId, {
  publicMetadata: {
    hasura_role: 'user',
    hasura_roles: ['user', 'anonymous'],
  },
});
\`\`\`
EOF
        ;;
    custom)
        cat >> "$INSTRUCTIONS_FILE" <<EOF
Set required metadata fields:

\`\`\`typescript
await clerkClient.users.updateUser(userId, {
  publicMetadata: {
    role: 'member',
    subscription_plan: 'pro',
    // Other custom fields
  },
});
\`\`\`
EOF
        ;;
esac

cat >> "$INSTRUCTIONS_FILE" <<EOF

## Testing

Test the JWT claims:

\`\`\`bash
./scripts/test-sessions.sh custom-claims
\`\`\`

## Important Notes

- Users must **sign out and sign in again** after template changes
- Claims are cached in the session - refresh won't pick up changes
- Use \`user.publicMetadata\` for custom claims (not privateMetadata)
- Validate claim presence in your code - they may be undefined

## Security

- Never include sensitive data in JWT claims
- Keep JWTs small (<4KB recommended)
- Claims are readable by client - don't include secrets
- Use \`privateMetadata\` for sensitive data (server-only access)

EOF

echo "✓ Created setup instructions: $INSTRUCTIONS_FILE"
echo ""

echo "Next Steps:"
echo "1. Review template: cat $TEMPLATE_FILE"
echo "2. Follow instructions in: $INSTRUCTIONS_FILE"
echo "3. Configure in Clerk Dashboard → JWT Templates"
echo "4. Test with: ./scripts/test-sessions.sh custom-claims"
echo ""
